title: Graham Greenfield
author: Graham Greenfield
email: grahamg@gmail.com
description: >-
  Thoughts about what software dev has turned into.
baseurl: "grahamg.xyz"
url: "https://gmgreenfield.github.io"
lang: en-US

theme: jekyll-whiteglass
plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - .git/
  - .github/
